### ISSUE TITLE
It always matches the sound to the first category listed

### ISSUE THREAD

**Issue by eyalis** [Caldarie/flutter_tflite_audio#10] opened 2021-03-20 14:29 UTC
When I try it, it always interprets the sound as the first category listed in the file

**Comment by Caldarie** [comment] 2021-03-20 14:57
Hi @eyalis,

To help better assist with your problem, can you provide more information? 

1. Are you using an emulator or device? 
2. Are you running the simulation on iOS/android?
3. Are you using your own model or the example provided?
4. What is your bufferSize?

**Comment by eyalis** [comment] 2021-03-20 15:07
Thank you @Caldarie for your quick answer, here it goes:

Describe the problem: When I try the example it always matches the first word of the category file.
1. Are you using a device or emulator?: I'm using a device: Samsung Galaxy S7 (the app requested me for permission and those were allowed).
2. Are you running the simulation on iOS/android? I'm running it on android
3. Are you using your own model or the example provided? I used the example provided first and I got that problem. Then I replaced the example model by my own model and I got the same problem.
4.  What is your bufferSize? 11050 (I'm using a teachable machine model)

Thanks for your help!

**Comment by Caldarie** [comment] 2021-03-20 18:49
Hmm, I’m that case:

1. Have you tried adjusting your bufferSize around? For example, 22050, 5000 etc
2. Can you tell me your sample rate?
3. Do you still get the same result if you run the “decodedWav” model in the example?

**Comment by eyalis** [comment] 2021-03-20 22:34
Thanks, so:

1. Have you tried adjusting your bufferSize around? For example, 22050, 5000 etc
Yes, I tried with: 22050, 5000, 7000, 30000, etc.

2. Can you tell me your sample rate?
I'm using the one that comes with the example which is 44100

3. Do you still get the same result if you run the “decodedWav” model in the example
No, that one works pretty good!

**Comment by Caldarie** [comment] 2021-03-21 00:44
Looking at your answers, we can rule down to one possibility.

I think the most likely reason why you’re not getting a response, is because your model isn’t trained well enough to distinguish your desired sound to other sounds/background noise.

Make sure that you increase the number of training examples and remove any prolong silences. (The goal is to make it as distinct as possible). Also for your background noise, you can add variations such as white noise, ambient noise etc. Try not to mix your voice in the background noise.

As for the reason why the GTM model  in the example is not working for you.. to be honest, it was hastily put together with minimal training examples; so unless you say the words very distinctly, it will not register.

**Comment by eyalis** [comment] 2021-03-21 13:16
Thank you for your answer, my model works well in the teachable machine (I have tested it with the tool they provide in the platform), I think it may be another problem, maybe related to my device configuration or something like that.

Thank you anyway, I'll keep trying and if I find what was the problem/solution, I'll let you know!!!

**Comment by Caldarie** [comment] 2021-03-21 14:33
Ah, i see. In that case, maybe you can tinker around with the sample rate. I heard that some people had better results with 16000

**Comment by Caldarie** [comment] 2021-03-26 13:26
Hi @eyalis,

I've updated the package (0.1.7) where you can now adjust the detection threshold of the model. I believe this should help fix the issue you are having. For example:

If your model is frequently matching the first category, simply adjust detectionThreshold to a lower value. 

Example on how to implement this:

```dart
final String model = 'assets/google_teach_machine_model.tflite';
final String label = 'assets/google_teach_machine_label.txt';
final String inputType = 'rawAudio';
final int sampleRate = 44100;
final int recordingLength = 44032;
final int bufferSize = 22050;
final int numOfInferences = 1;
final double detectionThreshold =  0.4; //Adjust this value here
```

Let me know if this fixes your problem

**Comment by eyalis** [comment] 2021-04-06 14:46
Hi @Caldarie thank you so much, I'll try it asap and let you know!

**Comment by cmalbuquerque** [comment] 2021-04-13 15:36
@Caldarie the same is happening to me. 
The inference always returns the first category 😕
I tested with both versions 0.6.2 and 0.7.1

**Comment by Caldarie** [comment] 2021-04-13 20:40
Hi @cmalbuquerque,

For testing purposes, can you tell me if you still see the same problem after lowering your detectionThreshold to maybe 0?

**Comment by cmalbuquerque** [comment] 2021-04-15 09:50
@Caldarie yes, I am using the following settings:
```
result = TfliteAudio.startAudioRecognition(
      numOfInferences: 1,
      inputType: 'rawAudio',
      sampleRate: 16000,
      recordingLength: 44032,
      bufferSize: 2000,
      detectionThreshold: 0,
    );
```
My sample rate is low as well as the bufferSize but I need to use these values in order to increase the time of recording. I will try to use other model with sounds more distinct and then I leave feedback here

**Comment by Caldarie** [comment] 2021-04-15 10:33
@cmalbuquerque

No problems at all, let me know the results of your other model.

Just be aware that detection threshold ignores any predictions where it’s probability doesn’t exceed the set value. For example:

If your detection threshold is set as 0.5 (50%) and your model predicts the audio label as “yes” at 0.4 (40%) and “no” at 0.1 (10%), your prediction will be ignored and hence the problem where the label matches the first label.

As mentioned in [comment #10](https://github.com/Caldarie/flutter_tflite_audio/issues/10#issuecomment-803492064) to @eyalis, it’s highly probable that the model isn’t trained well enough and you might need to train more data to rectify this issue .

Alternatively, you can lower your detection threshold, but I don’t advise going any lower than 0.30,  as you are forgoing your models  performance.

**Comment by cmalbuquerque** [comment] 2021-04-15 14:12
@Caldarie, 
Many thanks for the help and the detailed explanation! I used other model with `detectionThreshold: 0.4` and it works perfectly 😁

**Comment by Caldarie** [comment] 2021-04-15 15:00
@cmalbuquerque 

I’m very glad to hear that! 😁

**Comment by Caldarie** [comment] 2021-07-08 01:07
It has come to my attention that this problem may also be due to bufferSize.

Its possible that a higher bufferSize doesn't allow your device enough time to record, hence the problem where it always match the first category.To fix this, simply adjust the bufferSize to a lower value. 

Likewise, if your bufferSize is too low, the recording length will be too long and your model may possibly register it as background noise. Simply adjust the bufferSize to a higher value.

**Comment by amardeep-singh97** [comment] 2021-07-17 04:22
@Caldarie Thank you for this awesome package. I am facing the same issue. I tried all of the above solutions, none of them worked. I am thinking I might made some mistake while training the model on GTM. Can you suggest what should be "delay" and "duration" in class while training.

**Comment by Caldarie** [comment] 2021-07-17 04:34
Hi @amardeep-singh97,

To assist you with your problem, will it be possible for your to share your model?

**Comment by amardeep-singh97** [comment] 2021-07-17 05:14
@Caldarie Yes Here you go, Here we will get class 2 on saying "Help".
[converted_tflite (1).zip](https://github.com/Caldarie/flutter_tflite_audio/files/6834206/converted_tflite.1.zip)

**Comment by Caldarie** [comment] 2021-07-17 06:52
Hi @amardeep-singh97 

I ran through your example, and it seems that your were right about your model's accuracy (even after tuning the parameters). However, I have noticed that your model does at times pick up the sound after some slight delay but performs poorly when speaking too quickly or slowly.

1. In that case, may i ask as to how many samples you have trained? 
2. Have you considered training examples where you speak at different times of the recording length? For example, "help" at around 1.50 second  or 0.25 second mark. 
3. You may consider adding background noise to the sound 'help' to assist your model in differentiate with 'just' background noise.

Let me know how this works for you.

**Comment by amardeep-singh97** [comment] 2021-07-17 08:35
@Caldarie I think that too, i trained it with 60 background noise samples and 40 help samples. Sample size is 1 second on GTM. Can you suggest improvements

**Comment by Caldarie** [comment] 2021-07-17 08:58
@amardeep-singh97

Let me run some tests with the source code. As mentioned above, it seems that many people are experiencing the same problem as you. 

Oddly enough, this seems to only be a problem with GTM models.

**Comment by amardeep-singh97** [comment] 2021-07-17 09:24
@Caldarie Okay. Thank you for your support. Let us know what you find.

**Comment by Caldarie** [comment] 2021-07-17 10:32
Hi @amardeep-singh97,

I have tested my own GTM model provided in this repository, and had much better result with the following values:

``` dart
final double detectionThreshold = 0.3;
final int averageWindowDuration = 0; 
final int minimumTimeBetweenSamples = 0;
final int suppressionTime = 0;
final int minimumCount = 0;
``` 

Unfortunately, I haven't had much success with the model you have provided. It seems that your model (on average) considers most of the voice input "help" at around 20% confidence. I think the most likely explanation that your model has difficulty differentiating with background noise is because there's a lot of space in the recording length. For example:

**Audio input takes up a small portion of recording length**
<img width="57" alt="Screen Shot 2021-07-17 at 19 39 09" src="https://user-images.githubusercontent.com/42107315/126034367-b4a07ea7-0840-45b4-a625-77a891e847ac.png">
**Background noise**
<img width="59" alt="Screen Shot 2021-07-17 at 19 39 14" src="https://user-images.githubusercontent.com/42107315/126034364-f524a341-4c49-49f6-8eec-206be944f126.png">

As you can see in the first picture, it is very similar to the second picture, albeit the small recording input. Have you tried trimming this space?

**Comment by amardeep-singh97** [comment] 2021-07-18 15:29
@Caldarie I am training a new model with more variation in data. I will let you know if i face any issues. I'll consider arguments in your solution.

**Comment by Caldarie** [comment] 2021-07-19 05:07
@amardeep-singh97 keep us update! :)

**Comment by fabian-rump** [comment] 2021-08-06 08:33
I have the same problem but only on one device. I created a model with Google Teachable Machine and tested this on two devices:

**Samsung Galaxy S9 Plus**
The first label is always detected here.
The logged raw scores are: [NaN, NaN, NaN]

**Samsung Galaxy S20**
The detection works perfectly here

Both were tested under the same conditions.

Any suggestions?

**Comment by Caldarie** [comment] 2021-08-06 08:55
Hi @fabian-rump,

That’s a very peculiar problem.

With the S20, will it from time to time output NaNs?

As for S9, does this device always output NaNs? Or does it, from time to time, output a score?

**Comment by fabian-rump** [comment] 2021-08-06 09:12
The S20 outputs a NaN in one of hundreds of cases.
The S9 always outputs NaN. I haven't yet been able to get a score on the S9.

**Comment by Caldarie** [comment] 2021-12-03 14:47
Hey guys, I have found the cause and fixed the problem. Seems like it was right under my nose. Will now close the issue

**Closed as completed by Caldarie** 2021-12-03 14:47 UTC

**Comment by fradricast** [comment] 2023-07-11 07:09
How to get value raw score and recognition result tfliteaudio at the same ?
